- name: day 2 operations
  hosts: all
  become: yes
  tasks:
    - name: install mysql
      include_role:
        name: "{{ db_role1 }}"
      when: group_names|intersect(['databaseservers'])
    - name: "{{ web_role1 }}"
      include_role:
        name: php
      when: group_names|intersect(['webservers'])
    - name: "{{ web_role2 }}"
      include_role:
        name: apache
      when: group_names|intersect(['webservers'])
    - name: install php-mysql
      include_role:
        name: "{{ db_role2 }}"
      when: group_names|intersect(['databaseservers'])
