- name: day 2 operations
  hosts: all
  become: yes
  tasks:
    - name: install php
      include_role:
        name: php
      when: group_names|intersect(['webservers'])
    - name: install apache
      include_role:
        name: apache
      when: group_names|intersect(['webservers'])
    - name: install php-mysql
      include_role:
        name: php-mysql
      when: group_names|intersect(['webservers'])
    - name: install mysql
      include_role:
        name: mysql
      when: group_names|intersect(['databaseservers'])
